# Generated by Django 3.2.8 on 2021-10-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
