# Generated by Django 3.2.8 on 2021-10-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_data_of_birth_actor_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='actor',
        ),
    ]
