# Generated by Django 3.2.8 on 2021-10-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_movie_movie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='movies', to='movies.Actor'),
        ),
    ]
