# Generated by Django 3.2.8 on 2021-10-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211016_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergyproduct',
            old_name='allergy_id',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='allergyproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='allergy_id',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nutrition_id',
            new_name='nutrition',
        ),
    ]
